name: deploy-arun-aqua
on:
   workflow_dispatch:
jobs:
    deploy:
        
        runs-on: self-hosted
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
        steps:
                - name: Checkout code
                  uses: actions/checkout@v4

                - name: deploy with docker compose
                  run: docker-compose up -d --build
