name: deploy-arun-aqua
on:
   workflow_dispatch:
jobs:
    deploy:
        
        runs-on: self-hosted
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check Docker
              run: docker --version

            - name: Check Docker Compose
              run: docker compose version

            - name: Deploy with Docker Compose
              run: docker compose up -d --build